### ISSUE TITLE
Solution not working with Azure OpenAPI token

### ISSUE THREAD

**Issue by amartyaroy** [platisd/openai-pr-description#3]
Hi
I was trying to use this action in my personal exploration project. I am interested to know whether this solution works only with OpenAI token keys or Azure openAi keys is acceptable. As per microsoft documentation there shouldn't be much difference in using any of the keys but your solution is giving me issue of "openai.error.AuthenticationError: Incorrect API key provided:"
Although the keys are correctly generated.
Any hint regarding this?

**Comment by platisd** [comment]
Hi, never tried the Azure keys. You can try to see if the following snippet works with your key:

```python
import os
import openai

openai_api_key = os.environ.get("OPENAI_API_KEY", "<your-api-key>")
models = openai.OpenAI(api_key=openai_api_key).models.list().data
for model in models:
    print(model.id)
```

(I assume you have installed the OpenAI Python module, version 1.3 and older e.g.: `pip install --user openai==1.3.7`)

**Comment by cedricve** [comment]
We would need to use the Azure OpenAI import. I was planning to fork this and create my own GH Action. Are you willing to integrate it here? I can test for you.

    from openai import AzureOpenAI

    # Create the gpt-4o model client
    azure_openai_client = AzureOpenAI(
        api_key=os.environ['OPENAI_API_KEY'],
        azure_endpoint=os.environ['OPENAI_AZURE_ENDPOINT'],
        api_version=os.environ['OPENAI_API_VERSION']
    )

    corrected_chunk = azure_openai_client.chat.completions.create(
          model="gpt-4o",
          temperature=0,
          top_p=1,
          messages=[
              {"role": "user", "content": prompt},
          ],
      ).choices[0].message.content

**Comment by platisd** [comment]
@cedricve can you please try the action as `platisd/openai-pr-description@support_azure_openai` and tell me if it works?
I don't have access to Azure.

Two new keys are needed in the Action's configuration: `azure_endpoint` and `azure_openai_api_version`. Everything else stays the same.

![image](https://github.com/user-attachments/assets/f98b18c3-fab0-4d50-9558-0753f2f09624)

**Comment by platisd** [comment]
@cedricve do we actually need two separate keys for this? I see that in your [fork](https://github.com/platisd/openai-pr-description/commit/717107fdead473958c92aec6f32f8902a1f8f17b#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R10) you have also introduced `azure_openai_api_key` aside of `openai_api_key`.
Just by looking at the [AzureOpenAI class definition](https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py#L75), it feels like there should be one API key not two? :thinking:

**Comment by cedricve** [comment]
We might go with one single API key, but we definetly need to define the azure openai endpoint and api_version. I'm currently testing with my own fork, and let you know when I have something working.

**Comment by tvcsantos** [comment]
> @cedricve do we actually need two separate keys for this? I see that in your [fork](https://github.com/platisd/openai-pr-description/commit/717107fdead473958c92aec6f32f8902a1f8f17b#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R10) you have also introduced `azure_openai_api_key` aside of `openai_api_key`. Just by looking at the [AzureOpenAI class definition](https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py#L75), it feels like there should be one API key not two? 🤔

I can confirm that the changes are working 👍

**Comment by platisd** [comment]
@tvcsantos Justin to confirm: Are you referring to `platisd/openai-pr-description@support_azure_openai`?

**Comment by tvcsantos** [comment]
> @tvcsantos Justin to confirm: Are you referring to `platisd/openai-pr-description@support_azure_openai`?

Correct 👍
