### ISSUE TITLE
Ensure Consistent PR Review Process Regardless of Description Content

### ISSUE THREAD

**Issue by kalivaraprasad-gonapa-drishyaai** [platisd/openai-pr-description#5]
**Description:**
Currently, our GitHub Action skips execution if a pull request description is already populated. However, we want the action to enhance or verify the description in all cases, ensuring no PR bypasses our review standards unintentionally.

**Request:**
Please modify the workflow to run the action consistently, regardless of existing content in the PR description. This will help maintain thorough reviews and improve the quality and consistency of our PR descriptions.

**Comment by platisd** [comment]
Hi,
So if I understand this correctly, you'd like to be able to opt into overwriting the current PR description.
Sounds like an interesting feature, will look into it but feel free to contribute it instead if you want.

**Comment by platisd** [comment]
@kalivaraprasad-gonapa-drishyaai please try out the latest release of the Action and let me know if it's what you wanted. :+1: 
You should set the `overwrite_description` input to `true`.
